baseURL = "http://example.org/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 1
    [[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 2
    [[menu.nav]]
        name    = "Reservation"
        url     = "/reservation"
        weight  = 3
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/paintboard4.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/girl.jpg"
        heading = "HI, MY NAME IS JEWEL & I AM A"
        description = "WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL DESIGN DIRECTOR, WEB DESIGNER AND DEVELOPER. THIS SITE SHOWCASES SOME OF MY WORK."
        btn     = true
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "FACE PAINTER"
        [[params.banner.flipText]]
            title   = "YOGI"
        [[params.banner.flipText]]
            title   = "FRIEND"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    